# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'hangman_ui2.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Hangman(object):
    def setupUi(self, Hangman):
        Hangman.setObjectName("Hangman")
        Hangman.resize(314, 351)
        Hangman.setMinimumSize(QtCore.QSize(314, 351))
        Hangman.setMaximumSize(QtCore.QSize(314, 351))
        self.centralwidget = QtWidgets.QWidget(Hangman)
        self.centralwidget.setObjectName("centralwidget")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(100, 220, 69, 22))
        self.comboBox.setObjectName("comboBox")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(60, 10, 201, 51))
        self.textBrowser.setObjectName("textBrowser")
        self.graphicsView = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView.setGeometry(QtCore.QRect(30, 80, 131, 131))
        self.graphicsView.setObjectName("graphicsView")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(40, 220, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(190, 220, 101, 23))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(110, 270, 111, 20))
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(150, 250, 41, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_2.setGeometry(QtCore.QRect(170, 80, 131, 131))
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(140, 300, 51, 23))
        self.pushButton_2.setObjectName("pushButton_2")
        Hangman.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(Hangman)
        self.statusbar.setObjectName("statusbar")
        Hangman.setStatusBar(self.statusbar)

        self.retranslateUi(Hangman)
        QtCore.QMetaObject.connectSlotsByName(Hangman)

    def retranslateUi(self, Hangman):
        _translate = QtCore.QCoreApplication.translate
        Hangman.setWindowTitle(_translate("Hangman", "Hangman"))
        self.textBrowser.setHtml(_translate("Hangman", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:22pt; font-weight:600;\">HANGMAN</span></p></body></html>"))
        self.label.setText(_translate("Hangman", "Category"))
        self.pushButton.setText(_translate("Hangman", "Generate Word"))
        self.label_2.setText(_translate("Hangman", "Guess"))
        self.pushButton_2.setText(_translate("Hangman", "Enter"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Hangman = QtWidgets.QMainWindow()
    ui = Ui_Hangman()
    ui.setupUi(Hangman)
    Hangman.show()
    sys.exit(app.exec_())
